[phases.setup]
nixPkgs = ['python39', 'pip']

[phases.install]
cmds = ['pip install -r backend/requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'cd backend && gunicorn app:application --bind 0.0.0.0:$PORT'
